/**
 * profile.json → VFS seed generator (SPECIFICATION.md §6.7, Phase 2 spec D2).
 * Deterministic: frozen epoch, slug-derived ids, byte-stable output.
 * Run via `npm run generate:vfs`; CI fails if outputs drift from committed.
 *
 * Inputs:  scripts/vfs-base.json (frozen inherited shell items, raw JSON —
 *          field-preserving passthrough; carries fields outside VfsItem),
 *          src/lib/data/profile.json (via the typed profile module).
 * Outputs: static/json/hard_drive.json, src/lib/generated/seed_version.ts,
 *          src/lib/generated/vfs_ids.ts.
 */
import { createHash } from 'node:crypto';
import { execSync } from 'node:child_process';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { profile } from '../src/lib/profile';
import { SEED_EPOCH, build_portfolio } from '../src/lib/vfs_gen/build';
import type { VfsItem } from '../src/lib/types';

const C_DRIVE = 'cTbkbrM4qjwF3UfmCoFkEK';
const DESKTOP = 'nt1QdU9Sws26H26UNQZcQU';
const MY_COMPUTER_EXE = 'sWTYkZhdpSYCmXP7z6459v';
const IE_EXE = '2jpDfV5KSoYMArQnHgux5S';

/** Flipped per slice as real programs land (spec D13). */
const PROGRAM_URLS = {
    about_me: './programs/placeholder.svelte',
    my_cv: './programs/pdf_viewer.svelte',
    contact_me: './programs/placeholder.svelte',
};

const desktop_exe = (
    id: string,
    basename: string,
    url: string,
    icon: string,
): VfsItem => ({
    id,
    type: 'file',
    basename,
    name: `${basename}.exe`,
    storage_type: 'fake',
    url,
    ext: '.exe',
    parent: DESKTOP,
    size: 1024,
    executable: true,
    icon,
    children: [],
    date_created: SEED_EPOCH,
    date_modified: SEED_EPOCH,
    sort_option: 0,
    sort_order: 0,
});

// ---- assemble ----------------------------------------------------------
// Typed as VfsItem for validation, but the parsed objects are passed through
// by reference/spread — inherited fields outside the type (e.g. `hidden`)
// survive to the output untouched (field-preserving passthrough, spec D2).
const base = JSON.parse(
    readFileSync('scripts/vfs-base.json', 'utf8'),
) as Record<string, VfsItem>;
const built = build_portfolio(profile);

const exes: VfsItem[] = [
    desktop_exe(
        'p1AboutMeDesktopExe0001',
        'About Me',
        PROGRAM_URLS.about_me,
        '/assets/icons/about-me.png',
    ),
    desktop_exe(
        'p1MyCvDesktopExe0000001',
        'My CV',
        PROGRAM_URLS.my_cv,
        '/assets/icons/my-cv.png',
    ),
    desktop_exe(
        'p1ContactMeDesktopExe01',
        'Contact Me',
        PROGRAM_URLS.contact_me,
        '/assets/icons/contact-me.png',
    ),
];

const seed: Record<string, VfsItem> = { ...base };
const add = (item: VfsItem): void => {
    if (seed[item.id] != null) throw new Error(`id collision: ${item.id}`);
    seed[item.id] = item;
};
for (const item of Object.values(built.items)) {
    add(item.parent === '' ? { ...item, parent: C_DRIVE } : item);
}
for (const exe of exes) add(exe);

const c_drive = seed[C_DRIVE];
if (c_drive == null) throw new Error('C: drive missing from base');
seed[C_DRIVE] = {
    ...c_drive,
    children: [...c_drive.children, ...built.folder_ids, built.resume_file_id],
};

const desktop = seed[DESKTOP];
if (desktop == null) throw new Error('Desktop folder missing from base');
seed[DESKTOP] = {
    ...desktop,
    // §3.5 order (top-to-bottom on the desktop's left edge)
    children: [
        MY_COMPUTER_EXE,
        'p1AboutMeDesktopExe0001',
        'p1MyCvDesktopExe0000001',
        IE_EXE,
        'p1ContactMeDesktopExe01',
    ],
};

// ---- validate ----------------------------------------------------------
for (const [id, item] of Object.entries(seed)) {
    for (const child of item.children ?? []) {
        if (seed[child] == null) {
            throw new Error(`dangling child ${child} in ${id}`);
        }
    }
    if (
        item.parent != null &&
        item.parent !== '' &&
        seed[item.parent] == null
    ) {
        throw new Error(`dangling parent ${item.parent} in ${id}`);
    }
}

// ---- write -------------------------------------------------------------
const serialized = JSON.stringify(seed);
const version = createHash('sha256')
    .update(serialized)
    .digest('hex')
    .slice(0, 32);
writeFileSync('static/json/hard_drive.json', serialized);

mkdirSync('src/lib/generated', { recursive: true });
writeFileSync(
    'src/lib/generated/seed_version.ts',
    `// GENERATED by scripts/generate-vfs.ts — do not edit.\nexport const SEED_VERSION = '${version}';\n`,
);
writeFileSync(
    'src/lib/generated/vfs_ids.ts',
    `// GENERATED by scripts/generate-vfs.ts — do not edit.\n` +
        `export const PORTFOLIO_FOLDER_IDS: string[] = ${JSON.stringify(built.folder_ids)};\n` +
        `export const PORTFOLIO_ENTRY_IDS: string[] = ${JSON.stringify(built.entry_ids)};\n` +
        `export const PROJECTS_FOLDER_ID = '${built.projects_folder_id}';\n` +
        `export const RESUME_FILE_ID = '${built.resume_file_id}';\n`,
);
execSync(
    'npx prettier --write src/lib/generated/seed_version.ts src/lib/generated/vfs_ids.ts',
    { stdio: 'inherit' },
);
console.log(
    `generated: ${Object.keys(seed).length} items, SEED_VERSION ${version}`,
);
