/**
 * profile.json → VFS seed generator (SPECIFICATION.md §6.7, Phase 2 spec D2).
 * Deterministic: frozen epoch, slug-derived ids, byte-stable output.
 * Run via `npm run generate:vfs`; CI fails if outputs drift from committed.
 *
 * Inputs:  scripts/vfs-base.json (frozen inherited shell items, raw JSON —
 *          field-preserving passthrough; carries fields outside VfsItem),
 *          src/lib/data/profile.json (via the typed profile module).
 * Outputs: static/json/hard_drive.json, static/help.html,
 *          src/lib/generated/seed_version.ts,
 *          src/lib/generated/vfs_ids.ts, src/lib/generated/music.ts,
 *          static/assets/covers/* (this directory is OWNED here — cleared and
 *          rewritten every run, so a removed cover shows up as a tracked-file
 *          deletion the CI gate can actually see).
 *
 * NOTE ON THE MUSIC LIBRARY: the seed is built from the IN-MEMORY scan result,
 * never by importing `src/lib/generated/music.ts`. Importing our own output
 * would mean a run with a stale manifest writes a fresh one while seeding from
 * the previous one — converging only on a second run, while CI runs it once and
 * then diffs.
 */
import { createHash } from 'node:crypto';
import { join } from 'node:path';
import { execSync } from 'node:child_process';
import { mkdirSync, readFileSync, writeFileSync, rmSync } from 'node:fs';
import { parseFile } from 'music-metadata';
import { copy, fill_copy, profile } from '../src/lib/profile';
import { SEED_EPOCH, build_portfolio } from '../src/lib/vfs_gen/build';
import { COVER_DIR, scan_music } from '../src/lib/music/scan';
import type { ScanResult, TrackTags } from '../src/lib/music/scan';
import type { VfsItem } from '../src/lib/types';

/**
 * `music-metadata` -> the narrow shape `scan_music` needs.
 *
 * `{ duration: true }` is REQUIRED and not the default: without it
 * `format.duration` is undefined for files with no Xing/VBRI header, and the
 * scanner treats a missing duration as fatal because a zero duration makes
 * `progress_ratio` return 0 forever — a silently dead seek bar rather than a
 * visibly broken one.
 */
async function read_tags(path: string): Promise<TrackTags> {
    const meta = await parseFile(path, { duration: true });
    const picture = meta.common.picture?.[0];
    return {
        title: meta.common.title,
        artist: meta.common.artist,
        duration_s: meta.format.duration,
        picture:
            picture == null
                ? undefined
                : { data: picture.data, format: picture.format },
    };
}

/** Header for the generated music module — types live with the hand-written code. */
const MUSIC_HEADER = `// GENERATED by scripts/generate-vfs.ts \u2014 do not edit.
// Discovered from static/audio/music/<genre>/*.mp3; genres and their order come
// from profile.json. Run \`npm run generate:vfs\` after adding or removing files.
import type { Genre, Track } from '../music/manifest';

`;

const C_DRIVE = 'cTbkbrM4qjwF3UfmCoFkEK';
const DESKTOP = 'nt1QdU9Sws26H26UNQZcQU';
const MY_MUSIC = 'tjhEdnks6c4wPBWcqyoWQz';
const MY_COMPUTER_EXE = 'sWTYkZhdpSYCmXP7z6459v';

/**
 * `My Documents`, and the folder the Python REPL saves into.
 *
 * Generated here rather than hand-written into `scripts/vfs-base.json`,
 * because `src/` needs the Python folder's id at runtime and CLAUDE.md forbids
 * hand-editing `src/lib/generated/*`. Emitting it as `PYTHON_FOLDER_ID` puts
 * it under the CI freshness gate; a typo in either literal is caught by the
 * dangling parent/child validation below, which is the check that actually
 * bites (the hash gate compares generator output to committed output, so it
 * cannot see a literal that is wrong in both).
 */
const MY_DOCUMENTS = 'xpFolderMyDocuments0001';
const PYTHON_FOLDER = 'xpFolderPythonScripts01';
const IE_EXE = '2jpDfV5KSoYMArQnHgux5S';

/** Flipped per slice as real programs land (spec D13). */
const PROGRAM_URLS = {
    about_me: './programs/about_me.svelte',
    my_cv: './programs/pdf_viewer.svelte',
    contact_me: './programs/contact_me.svelte',
};

const desktop_exe = (
    id: string,
    basename: string,
    url: string,
    icon: string,
): VfsItem => ({
    id,
    type: 'file',
    basename,
    name: `${basename}.exe`,
    storage_type: 'fake',
    url,
    ext: '.exe',
    parent: DESKTOP,
    size: 1024,
    executable: true,
    icon,
    children: [],
    date_created: SEED_EPOCH,
    date_modified: SEED_EPOCH,
    sort_option: 0,
    sort_order: 0,
});

// ---- assemble ----------------------------------------------------------
// Typed as VfsItem for validation, but the parsed objects are passed through
// by reference/spread — inherited fields outside the type (e.g. `hidden`)
// survive to the output untouched (field-preserving passthrough, spec D2).
const base = JSON.parse(
    readFileSync('scripts/vfs-base.json', 'utf8'),
) as Record<string, VfsItem>;
const built = build_portfolio(profile);

const exes: VfsItem[] = [
    desktop_exe(
        'p1AboutMeDesktopExe0001',
        'About Me',
        PROGRAM_URLS.about_me,
        '/assets/icons/about-me.png',
    ),
    desktop_exe(
        'p1MyCvDesktopExe0000001',
        'My CV',
        PROGRAM_URLS.my_cv,
        '/assets/icons/my-cv.png',
    ),
    desktop_exe(
        'p1ContactMeDesktopExe01',
        'Contact Me',
        PROGRAM_URLS.contact_me,
        '/assets/icons/contact-me.png',
    ),
];

const seed: Record<string, VfsItem> = { ...base };
const add = (item: VfsItem): void => {
    if (seed[item.id] != null) throw new Error(`id collision: ${item.id}`);
    seed[item.id] = item;
};
for (const item of Object.values(built.items)) {
    add(item.parent === '' ? { ...item, parent: C_DRIVE } : item);
}
for (const exe of exes) add(exe);

const c_drive = seed[C_DRIVE];
if (c_drive == null) throw new Error('C: drive missing from base');
seed[C_DRIVE] = {
    ...c_drive,
    // My Documents FIRST, as XP orders it — Explorer and `ls` both render this
    // array verbatim, so the order here is the order a visitor sees.
    children: [
        MY_DOCUMENTS,
        ...c_drive.children,
        ...built.folder_ids,
        built.resume_file_id,
    ],
};

// ---- My Music: discovered from static/audio/music/<genre>/*.mp3 ---------
// The FOLDER is the source of truth (the owner drops files in and regenerates);
// profile.json only declares which genres exist, their display names and their
// order. Explorer mirrors that: My Music holds a folder per genre, each holding
// its tracks. Entries point at the SAME static URLs the player uses, so no
// bytes are duplicated — only metadata.
const my_music = seed[MY_MUSIC];
if (my_music == null) throw new Error('My Music folder missing from base');

const music: ScanResult = await scan_music(profile.music.genres, read_tags);

for (const genre of music.genres) {
    seed[genre.id] = {
        id: genre.id,
        type: 'folder',
        name: genre.name,
        basename: genre.name,
        ext: '',
        icon: '/images/xp/icons/MyMusic.png',
        parent: MY_MUSIC,
        children: genre.tracks.map((t) => t.id),
        date_created: SEED_EPOCH,
        date_modified: SEED_EPOCH,
        sort_option: 0,
        sort_order: 0,
    };
    for (const track of genre.tracks) {
        seed[track.id] = {
            id: track.id,
            type: 'file',
            basename: track.title,
            name: `${track.title}.mp3`,
            ext: '.mp3',
            storage_type: 'remote',
            url: track.url,
            // KB, per VfsItem.size — a byte value renders as "512,986 KB".
            size: track.size_kb,
            parent: genre.id,
            children: [],
            date_created: SEED_EPOCH,
            date_modified: SEED_EPOCH,
            sort_option: 0,
            sort_order: 0,
        };
    }
}
seed[MY_MUSIC] = {
    ...my_music,
    children: [...my_music.children, ...music.genres.map((g) => g.id)],
};

// ---- My Documents \ Python --------------------------------------------
// Where the Python REPL persists a visitor's saved scripts. `My Documents` is
// the XP-authentic home for a visitor's own files and the drive had no
// equivalent; the subfolder keeps saved scripts from colliding with anything
// added later.
seed[MY_DOCUMENTS] = {
    id: MY_DOCUMENTS,
    type: 'folder',
    name: 'My Documents',
    basename: 'My Documents',
    ext: '',
    icon: '/images/xp/icons/MyDocuments.png',
    starting_point: true,
    parent: C_DRIVE,
    children: [PYTHON_FOLDER],
    date_created: SEED_EPOCH,
    date_modified: SEED_EPOCH,
    sort_option: 0,
    sort_order: 0,
};
seed[PYTHON_FOLDER] = {
    id: PYTHON_FOLDER,
    type: 'folder',
    name: 'Python',
    basename: 'Python',
    ext: '',
    icon: '/images/xp/icons/FolderClosed.png',
    parent: MY_DOCUMENTS,
    children: [],
    date_created: SEED_EPOCH,
    date_modified: SEED_EPOCH,
    sort_option: 0,
    sort_order: 0,
};

const desktop = seed[DESKTOP];
if (desktop == null) throw new Error('Desktop folder missing from base');
seed[DESKTOP] = {
    ...desktop,
    // §3.5 order (top-to-bottom on the desktop's left edge)
    children: [
        MY_COMPUTER_EXE,
        'p1AboutMeDesktopExe0001',
        'p1MyCvDesktopExe0000001',
        IE_EXE,
        'p1ContactMeDesktopExe01',
    ],
};

// ---- validate ----------------------------------------------------------
for (const [id, item] of Object.entries(seed)) {
    for (const child of item.children ?? []) {
        if (seed[child] == null) {
            throw new Error(`dangling child ${child} in ${id}`);
        }
    }
    if (
        item.parent != null &&
        item.parent !== '' &&
        seed[item.parent] == null
    ) {
        throw new Error(`dangling parent ${item.parent} in ${id}`);
    }
}

// ---- write -------------------------------------------------------------
const serialized = JSON.stringify(seed);
const version = createHash('sha256')
    .update(serialized)
    .digest('hex')
    .slice(0, 32);
writeFileSync('static/json/hard_drive.json', serialized);

mkdirSync('src/lib/generated', { recursive: true });
/*
 * The generator OWNS static/assets/covers: it is cleared and rewritten every
 * run. Without that, a cover whose track is gone simply lingers — and an
 * unchanged file produces no diff, so no gate could ever see it. Clearing
 * turns a removal into a tracked-file deletion the CI check can catch.
 */
rmSync(COVER_DIR, { recursive: true, force: true });
mkdirSync(COVER_DIR, { recursive: true });
for (const cover of music.covers) {
    writeFileSync(join(COVER_DIR, cover.filename), cover.data);
    if (cover.data.byteLength > 400 * 1024) {
        console.warn(
            `  warn: cover ${cover.filename} is ${String(Math.round(cover.data.byteLength / 1024))}KB — ` +
                'embedded art is often 3000x3000 and is committed to git forever',
        );
    }
}

/*
 * The Help page.
 *
 * `static/help.html` is served as a PLAIN FILE — it is outside the bundle and
 * cannot import profile.json — so the owner's name and repository URL were
 * spelled there a second time, free to drift the day either changed. Filling a
 * template here makes profile.json the only place they are written, the same
 * way the drive seed already works.
 */
{
    const repo_url = profile.projects[0]?.url;
    if (repo_url == null || repo_url === '') {
        throw new Error(
            'profile.json: projects[0].url is what help.html links to as the ' +
                'source repository — it cannot be empty',
        );
    }
    const template = readFileSync('scripts/help.template.html', 'utf8');
    const body = template.slice(template.indexOf('-->') + 4);
    const filled = fill_copy(body, {
        name: profile.meta.name,
        repoUrl: repo_url,
        loginAccountsHint: copy.loginHints.accounts.join(' '),
    });
    const left = [...filled.matchAll(/\{(\w+)\}/g)].map((m) => m[1]);
    if (left.length > 0) {
        throw new Error(
            `help.template.html has unfilled placeholders: ${left.join(', ')}`,
        );
    }
    writeFileSync(
        'static/help.html',
        `<!-- GENERATED by scripts/generate-vfs.ts from scripts/help.template.html \u2014 do not edit. -->\n${filled}`,
    );
}

writeFileSync(
    'src/lib/generated/music.ts',
    `${MUSIC_HEADER}export const TRACKS: readonly Track[] = ${JSON.stringify(
        music.genres.flatMap((g) =>
            g.tracks.map((t) => ({
                id: t.id,
                title: t.title,
                artist: t.artist,
                filename: t.filename,
                url: t.url,
                size_kb: t.size_kb,
                duration_s: t.duration_s,
                genre: t.genre,
                cover: t.cover,
                cover_box: t.cover_box,
            })),
        ),
        null,
        4,
    )};\n\nexport const GENRES: readonly Genre[] = ${JSON.stringify(
        music.genres.map((g) => ({ id: g.id, dir: g.dir, name: g.name })),
        null,
        4,
    )};\n`,
);

writeFileSync(
    'src/lib/generated/seed_version.ts',
    `// GENERATED by scripts/generate-vfs.ts — do not edit.\nexport const SEED_VERSION = '${version}';\n`,
);
writeFileSync(
    'src/lib/generated/vfs_ids.ts',
    `// GENERATED by scripts/generate-vfs.ts — do not edit.\n` +
        `export const PORTFOLIO_FOLDER_IDS: string[] = ${JSON.stringify(built.folder_ids)};\n` +
        `export const PORTFOLIO_ENTRY_IDS: string[] = ${JSON.stringify(built.entry_ids)};\n` +
        `export const PROJECTS_FOLDER_ID = '${built.projects_folder_id}';\n` +
        `export const RESUME_FILE_ID = '${built.resume_file_id}';\n` +
        `export const MY_DOCUMENTS_ID = '${MY_DOCUMENTS}';\n` +
        `export const PYTHON_FOLDER_ID = '${PYTHON_FOLDER}';\n`,
);
execSync(
    'npx prettier --write src/lib/generated/seed_version.ts src/lib/generated/vfs_ids.ts src/lib/generated/music.ts',
    { stdio: 'inherit' },
);
console.log(
    `generated: ${Object.keys(seed).length} items, SEED_VERSION ${version}`,
);
